### ISSUE TITLE
Initial testing

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/search_api#1]
Great to see Search API on Backdrop, I could bring many more projects to the platform when this is working. 

Here's what I found out with the very initial testing
- Can't enable search facets (facetapi module is missing) (This issue is not urgent for me)
- Can't create a server at /admin/config/search/search_api/add_server (Message: "There are no service classes available for the Search API. Please install a module that provides a service class to proceed."). So Search API database module would be the best solution to start with. (Blocker)

**Comment by mazzech** [comment]
It also lead to errors when saving an existing node after making changes to the node content.

**Comment by docwilmot** [comment]
Added Search API database module. Facetapi uses CTools, so I suspect porting may be a bit more work than I'm in the mood for right now.

**Comment by mazzech** [comment]
Cool, thank you for the DB module:-) Meanwhile I managed to
- create server instance
- create server index
- choose indexed fields

But I get a white screen when making changes to https://mysite.com/de/admin/config/search/search_api/index/NAMEOFINDEX/workflow

And log messages like Notice: Use of undefined constant ENTITY_CUSTOM - assumed 'ENTITY_CUSTOM' in search_api_access_delete_page() (Zeile 2681 von /home/www-data/backdrop.mazze.ch/modules/search_api-1.x-1.x 2/search_api.module).


![screen shot 2019-02-26 at 10 12 24](https://user-images.githubusercontent.com/5985692/53401074-69499200-39af-11e9-8fd0-9c75b6c79d47.png)
![screen shot 2019-02-26 at 10 10 56](https://user-images.githubusercontent.com/5985692/53401075-69e22880-39af-11e9-80bf-144c7c4e489a.png)
![screen shot 2019-02-26 at 10 09 55](https://user-images.githubusercontent.com/5985692/53401076-69e22880-39af-11e9-9fe8-87c5e1639b44.png)

**Comment by herbdool** [comment]
Those error messages have to do with making entities exportable to Features. https://www.drupal.org/node/1021526. I presume we don't want to support that anymore.

**Comment by docwilmot** [comment]
@herbdool thanks for the pointer. Don't know if I'll be working on this anytime soon though. Just remembered I'd also started some work on FacetAPI module as well too, will push that now. If there is great demand for search modules, someone, maybe me, can take this up if users ask for it enough.

**Comment by mazzech** [comment]
Thank you @docwilmot :-) Good search is key for most of my projects in the long term, however it's not urgent at this point. But I guess with D7 EOL, this will be more of an issue for many Backdroppers

**Comment by retrodans** [comment]
Just thought it worth stating that we are looking into backdrop at the moment, and `search_api` may become a blocker for us.  I intend to test it out now to see how much works for us, and whether it works enough for the majority of our use cases.  But if any testing is needed, please do just let us know, and I will try to help where possible.

**Comment by mazzech** [comment]
Thanky you @retrodans Are there specific elements of Search API who are "more of a blocker" than others?

**Comment by retrodans** [comment]
Thanks for the quick reply @mazzech after some initial tests, some higher priority issues I would raise (based on our example site) are:

- [ ] **search_views** - I cannot create a new view which filters by a search index (I have search_api, search_db, search_api_views all enabled) and have a lot of broken_handlers in my views
- [ ] **search_facets** - is also used on a lot of our sites (this is the ctools issue mentioned here https://github.com/backdrop-contrib/search_api/issues/1#issuecomment-466784004)
- [ ] **Notices** -  (which I think you mentioned in https://github.com/backdrop-contrib/search_api/issues/1#issuecomment-467359343)

More issues may come up as those get resolved though.

If useful, I can create separate issue tickets for each of these,
Dan

**Comment by mazzech** [comment]
Hi Dan, 

I created a Search Function just by using Views and Exposed Filters, without any search-related module: https://lag.mazzemedia.ch/suchen

(try e.g. "Aargau" as keyword, the region this organisation is located at, this will lead to many results)

I can also restrict the search by field, content type, etc. It's not the most elegant way performance-wise, but it works. 

I never tried, but even "Filter by Content Type" could be achieved quite easely. So Facet API could also be a #2 priority.

What I really miss on Backdrop now is Search Autocomplete. It's a typical upselling feature in RFPs, and both customers and users like it.

**Comment by mazzech** [comment]
Oh, and I forgot "Search > Did you mean..." with similar expressions, correctly spelled versions etc. I know that in D7 it took an Apache SOLR server for this, but people really want a search to have those features, IMO.

**Comment by retrodans** [comment]
On that, ultimately **SOLR** will also be a blocker on some of our sites (but not all), and having search_api working feels like a step towards being able to do that.

Thanks for the pointers on just using core, they are valid points, and things that could be considered.

@mazzech is the plan (roadmap) to drop this module and do everything in core instead btw? Or do we still need some issues and pull requests made to get this module over the line?

**Comment by mazzech** [comment]
I have no idea what the roadmap is, but there were some discussions, and I proposed improved Search to be an key feature in a future release. Back then, the priority did not seem that high or urgent. But in the long term, good search function is important for increasing the adoption rate. (There might be 60k+ D7 websites running Search API https://www.drupal.org/project/usage/search_api)

**Comment by retrodans** [comment]
For sure, what with the eol being late next year, decisions are being made now (at least for us), and so anything lacking we need to look at and work out if we can help, and if we can, how much time would be required.  Search (and facets) feels like a bit of a beast, but I could be wrong.

I assume the module was (close to) a direct copy from the Drupal site, so wonder why some things wouldn't work, and also when was that copy done (as we probably would want some of the changes since to also be copied across).

**Comment by mazzech** [comment]
We should try to bring this up at the next DEV meeting, but let me check if it's not in the list already 

@olafgrabienski did you talk about it recently in the core team?

**Comment by olafgrabienski** [comment]
> did you talk about it recently?

@mazzech I don't recall an extensive discussion about search at the weekly meetings (didn't attend every meeting, though).

**Comment by retrodans** [comment]
Thanks for the info, can I ask what the dev meetings are, when they are, and who are in them?  Partly out of curiosity, partly as it will help know when this might get discussed.

@mazzech if it can be mentioned, that would be great, I think search/facets are really the only thing blocking us (as an agency) from considering backdrop as an option, so would be good to know what the plan/timeline is, and whether we could/should help with it (even if just to test).

**Comment by olafgrabienski** [comment]
@retrodans You'll find information about the weekly video meetings (on Thursdays) on the page https://backdropcms.org/support/resources. Look for the section "Community Meetings".

**Comment by mazzech** [comment]
Hi @retrodans great, let me know if I can help you with both testing and define testing scenarios.

Maybe @stpaultim (developer relations) also wants to chime in here...? Dan currently has a look at Search API, which is important for Backdrop adoption rate, ten of thousands D7 installations out there.

**Comment by retrodans** [comment]
Thanks for the information.  It sounds best if I listen on this ticket until you have your meeting on Thursday, as some updated on the importance of SearchAPI will be getting discussed there.  Does this sound correct?

Thanks again for the help with this.

Dan

**Comment by olafgrabienski** [comment]
@retrodans For reference, there's also the core meta issue [Improve core search](https://github.com/backdrop/backdrop-issues/issues/1332).

**Comment by stpaultim** [comment]
@retrodans - Just to be clear, the dev meeting (happening in just over an hour today) is an open meeting to discuss Backdrop dev issues. Anyone is welcome to attend and comment on issues that are important to them. 

This issue will be raised. But, the amount of attention it gets will depend upon who is attending and how interested they are in this issue. https://backdropcms.org/news/meetings

This issue is brought up frequently. I think we are just lacking someone with both the specific skill set and interest in the issue to push it forward (in my opinion).

**Comment by mazzech** [comment]
Hi @retrodans, we discussed this issue at yesterday's meeting (as Tim says, feel free to join us next week or anytime soon). Here's my quick summary of the discussion.

- All participants see that there's a lot of room for improvement regarding search in Backdrop
- There has NOT been much discussion about core search recently, also because the issue has no advocate who push things forward (well, that might change now;-)
- Search API is considered to be a great module, but for a number of reasons it should remain a contrib module (I agree with that)

So nothing can prevent us from getting started:-)

I am just curious... are you a developer, or do you have a development team available?

**Comment by retrodans** [comment]
Hi @mazzech I am a php/python developer, and at my core, specialise in Drupal (hence this work now, as we are looking at options for Drupal7 clients that are not ready for a fresh Drupal8 site).  I am part of an agency in oxford, so there are other developers.  We are still trying to confirm if we can assign budget/resource to Bootstrap, although I am hoping we can do.  Search_api is the only real blocker I think, all other modules are minor, and either have alternatives or are easy for us to migrate ourselves for the community if we come to them.

**Comment by herbdool** [comment]
I believe that search_api (and search_api_db) are probably pretty close to being usable. I don't have a need for them so I haven't worked on them, but I have tested them. The one main thing that wasn't working for me was when creating a View. I attempted some debugging but stopped because of other priorities.

**Comment by earlyburg** [comment]
Hello all - I just read through this thread and wanted to update the group about the remaining steps on my path to an official release.
I will be testing the facet_api integration and resolving some issues I have been running into with tests, and then I hope to be able to create an official release along with the search_api_solr module. I welcome any and all feedback on functionality and appearance, and I appreciate all the support. Thanks!

**Comment by docwilmot** [comment]
reminder that facetapi code is quite very pre-alpha.

**Comment by earlyburg** [comment]
@docwilmot WIthout your hard work on this I would not have gotten this far. I am doing a bit of testing now, so down the proverbial rabbit-hole I go. Thanks for the heads-up, I appreciate it.

**Comment by mazzech** [comment]
Great to see this evolving... let me know if I can help with testing.

**Comment by earlyburg** [comment]
@mazzech I really appreciate the offer!
Search API is definitely ready for testing. I would like to get an official release for this out before christmas, so I welcome any testing and subsequent feedback. So far it's working very well for me. The only real issue right now is the status of 
https://github.com/backdrop-contrib/facetapi
which I have been working on with the kind assistance of docwilmot. Facet API is required for the Search API Search Facets sub-module to function. I collaborated a couple of days ago with docwilmot and we agreed that I would make two adjustments to my last pull request:
https://github.com/backdrop-contrib/facetapi/pull/4
and then the Facet Api should be ready for testing with search API.
Some things I have not tested are:
Does search API play well with Backdrops native search functionality when both modules are activated.
Does the output from the module display well in Backdrops theme layer? I only tested it in my dev sites default theme
Not sure if views integration is 100% matching the D7 standard. I got it working but did not really test it completely.
I appreciate it...

**Comment by mazzech** [comment]
![Screenshot 2020-12-06 at 14 31 49](https://user-images.githubusercontent.com/5985692/101281851-d4a1d400-37d1-11eb-820b-91c53eed2f4a.png)
Hi @earlyburg 

thank you... I can't installe the Facet module, however, the search module seems to work quite well. See screenshot for what I see after activating Search API and Facetapi.

I will continue to check out Search API... (just curious... are there also plans to port the Autocomplete module?). Thank yo anyway for your work:-)

**Comment by mazzech** [comment]
OK, can't install Search API either... same error with entity plus.

**Comment by earlyburg** [comment]
Closing this issue due to it's age and lack of relevance.
