### ISSUE TITLE
Undefined function entity_view().

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#13]
When attempting to index I get this error:

> Error: Call to undefined function entity_view() in SearchApiAlterAddViewedEntity->alterItems() (line 77 of /app/modules/search_api/includes/callback_add_viewed_entity.inc).

I believe this happens when I enable the option to add the "Complete Entity View" in the filters.

Changing to `entity_plus_view()` appears to work.

**Comment by earlyburg** [comment]
This has been fixed.
https://github.com/backdrop-contrib/search_api/commit/817fd66473700a62918a69693178acf6cd038440

**Comment by earlyburg** [comment]
I'll do  a new release after I squash some more bugs...

**Comment by earlyburg** [comment]
Fixed with latest release:
https://github.com/backdrop-contrib/search_api/releases/tag/1.x-1.0.02
closing this issue.
