### ISSUE TITLE
Excerpt Views field is broken handler

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#14]
When I add the excerpt it says it's broken. 

In `includes/processor_highlight.inc` I changed `$language->language` to `$language->langcode`. But that isn't the only issue. I also see:

> _views_create_handler - loading handler handler(handler type: field) failed: class entity_views_handler_field_text could not be loaded. Verify the class file has been registered in the corresponding .info-file (files[]).

In `/contrib/search_api_views/views/search_api_views.views.inc` line 110 I changed to `$table['search_api_excerpt']['field']['handler'] = 'entity_plus_views_handler_field_text';` and that fixed the broken handler.

**Comment by herbdool** [comment]
Related to the except, I'm not sure if this is a general error or not, but I notice the excerpt is only highlighting the title field. I'm going to test a bit more before reporting.

**Comment by earlyburg** [comment]
This has been fixed.
https://github.com/backdrop-contrib/search_api/commit/5643c7270d005b08ca110f6a45b57116fa09b90d
Thanks for the assistance, I appreciate it.

**Comment by earlyburg** [comment]
This has been fixed with the latest release:
https://github.com/backdrop-contrib/search_api/releases/tag/1.x-1.0.02
Closing this issue.
