### ISSUE TITLE
Complete Entity view should show "default" view mode as option

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#16]
Currently it allows Full Content, Teaser, etc, but not the Default - this is a new Backdrop view mode which is used as a fallback.

**Comment by earlyburg** [comment]
@herbdool - Hi, can you give me an example where this is used elsewhere? I'm mindful that I probably don't know enough about this entity view mode. Thank you for your help, I appreciate it.

**Comment by earlyburg** [comment]
Closed due to inactivity >= 30 days.
