### ISSUE TITLE
Simplify README

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/search_api#2]
The README is huge with way too much text for someone just wanting basic information about the module.

I suggest minimising the README info to match https://github.com/backdrop-ops/module-template/blob/master/README.md and moving the bulk of the detailed info to the [wiki](https://github.com/backdrop-contrib/search_api/wiki).

**Comment by earlyburg** [comment]
@BWPanda Hi,
I have created a wiki page and updated the README as you suggested.
https://github.com/backdrop-contrib/search_api/commit/fc8ec31fc2d7b1c423667db765b74ba614c707c3
I tried to be consistant with my re-write. Thanks for pointing this out.
I'll wait for a few days before I do a release that will include this fix in case of any feedback for changes.
