### ISSUE TITLE
Fix needed to support a proposed date module fix

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#24]
Fix needed to support an update to date module: https://github.com/backdrop/backdrop-issues/issues/4267. There's a simple fix in the d7 queue for it. Would be good to get that fix in here so the date module can be fixed in core.

Thanks!

**Comment by earlyburg** [comment]
Thanks for letting me know. I will take a look asap.

**Comment by earlyburg** [comment]
@herbdool - I looked at this. It will take additional time. Please stay tuned.
This is actually a bit complex. I'm not sure how I am going to test against a core fix that has not been applied yet unless I branch core and do the update to the date module, then test against it. I am understanding the patch in d7 but I need to figure out how and where this may apply to search_api

**Comment by jenlampton** [comment]
The core issue has [a PR](https://github.com/backdrop/backdrop/pull/2868) and you can use that for your testing. You can grab a patch version of the PR at https://github.com/backdrop/backdrop/pull/2868.patch if that's easier.

**Comment by laryn** [comment]
@earlyburg Did you have a chance to look at this? I think the core issue is blocked until this is resolved here.

**Comment by laryn** [comment]
Core issue has been merged. Closing this one.
