### ISSUE TITLE
Entity Plus constants now start with prefix ENTITY_PLUS_XXX

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api#25]
Recently, in the Entity Plus issue queue (https://github.com/backdrop-contrib/entity_plus/issues/115),  someone reported an undefined constant ENTITY_CUSTOM error invoked by Search API.

Please note that, since [this commit](https://github.com/backdrop-contrib/entity_plus/commit/b7ccd32a96ba4593f8a2c94f8f6dc59008ed535b) in Oct 2021, Entity Plus has prefixed all its constants as follows:

ENTITY_PLUS_CUSTOM

etc. This was done by @laryn to avoid a clash with Entity UI, which also defines those contants.

There are several instances in Search API where the old constants are still in use.

**Comment by earlyburg** [comment]
This seems like an easy fix. I will try to get this done by the end of the week if possible.
Thanks for the detailed synopsis, I appreciate it.

**Comment by earlyburg** [comment]
This has been done.
https://github.com/backdrop-contrib/search_api/releases/tag/1.x-1.0.06
Thank you for your patience. Closing this issue.
