### ISSUE TITLE
Search API Views: Entity Error

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/search_api#27]
I wanted to create a search view but can't chose the rendered entity formatter. The following error occured:
`Error: Class 'EntityFieldHandlerHelper' not found in SearchApiViewsQuery->get_result_wrappers() (line 587 of /mypath/modules/search_api/contrib/search_api_views/includes/query.inc).`

**Comment by earlyburg** [comment]
This may be a result of recent changes to entity plus module. I will investigate further.

**Comment by djzwerg** [comment]
Thanks a lot @earlyburg

**Comment by earlyburg** [comment]
Please download the latest new release of this module
https://github.com/backdrop-contrib/search_api/releases/tag/1.x-1.0.06
Let me know if it resolves this issue.
Thanks for your patience with this.

**Comment by djzwerg** [comment]
Thanks! I can confirm that this issue has been solved.

**Comment by djzwerg** [comment]
Well I'm sorry. As I can see for now it is not possible to create a search (index) view of the rendered entity. Only fields are available:
![grafik](https://user-images.githubusercontent.com/49948628/154818392-1f0e1aef-2609-4dc1-b41b-f2fb9b38c082.png)

**Comment by earlyburg** [comment]
This is not an issue with Search API per se. 
Unless you have a php message this should be categorized as a feature request.

**Comment by djzwerg** [comment]
In Drupal 7 I can create an unformatted list of the rendered entity. I thought it was a bug, too. Sorry, my fault.
