### ISSUE TITLE
Undefined constant ENTITY_CUSTOM

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/search_api#29]
This constant is [defined in Entity UI module](https://github.com/backdrop-contrib/entity_ui/blob/c0078bc295b757bbd5a0a1e65daf09b8ed92b59d/entity_ui.module), not entity plus, which defines ENTITY PLUS CUSTOM. A solution would be to add Entity UI as dependency, but it might be easier just to define the constant in the code itself.

**Comment by robertgarrigos** [comment]
Even better, change ENTITY CUSTOM constant to ENTITY PLUS CUSTOM ([https://github.com/backdrop-contrib/entity_plus/issues/115#issuecomment-1065889187](https://github.com/backdrop-contrib/entity_plus/issues/115#issuecomment-1065889187))

**Comment by earlyburg** [comment]
@robertgarrigos 
this commit from 23 days ago should have fixed this
https://github.com/backdrop-contrib/search_api/commit/b99e35882c87660ca37fa3e4fa0f26d59731dc1e
In addition, I have verified that there are no instances of this string (ENTITY_CUSTOM) in the search_api and search_api_page module.
Latest release is here:
https://github.com/backdrop-contrib/search_api/releases/tag/1.x-1.0.06
Closing this ticket, as there is nothing to fix.

**Comment by robertgarrigos** [comment]
Indeed, latest update fixed this. Thanks.
