### ISSUE TITLE
Error: Class 'EntityFieldHandlerHelper' not found

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/search_api#30]
> Error: Class 'EntityFieldHandlerHelper' not found in SearchApiViewsQuery->get_result_wrappers() (line 587 of /app/modules/contrib/search_api/contrib/search_api_views/includes/query.inc).

There are a few cases where 'EntityFieldHandlerHelper' should be 'EntityPlusFieldHandlerHelper'.

**Comment by danksearle** [comment]
my bad, this code is in a release. Thanks!
