### ISSUE TITLE
Search relevance field

### ISSUE THREAD

**Issue by keiserjb** [backdrop-contrib/search_api#35]
I tried to add a field for search relevance and the handler was always broken in the view.

Line 102 of search_api_views.views.inc needs to be
`$table['search_api_relevance']['field']['handler'] = 'entity_plus_views_handler_field_numeric';`  Then it works.

**Comment by earlyburg** [comment]
I will have a look at this tomorrow. Thanks for pointing this out.

**Comment by herbdool** [comment]
@earlyburg created PR https://github.com/backdrop-contrib/search_api/pull/39

**Comment by argiepiano** [comment]
This fix LGTM. Ready to be committed.

**Comment by argiepiano** [comment]
Hi @herbdool. Since your PR is from Dec, I can go ahead and merge this as a bug squad task, since @earlyburg has not responded. LMK
