### ISSUE TITLE
_element_validate_integer not found

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#38]
`TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, function "_element_validate_integer" not found or invalid function name in _form_validate() (line 1497 of /app/httpdocs/core/includes/form.inc).`

I get this when trying to delete a search index from the individual index such as `admin/config/search/search_api/index/default_node_index/edit`. If I delete from the index list then it's okay.

It might be from being called in `search_api_admin_index_edit` of `search_api.admin.inc`. The function existed in Drupal 7 but not in Backdrop. Some other modules like Rules just copy the function and make it specific to the module. Or better, would be to change the form element (cron_limit) to a number field and use that https://docs.backdropcms.org/api/backdrop/core!includes!drupal.inc/function/element_validate_integer/1

**Comment by herbdool** [comment]
I can create a PR

**Comment by herbdool** [comment]
I almost created a PR but noticed it was already fixed. So instead, would you be able to create a new release @earlyburg? (After merging some bugs?) Thanks.

**Comment by argiepiano** [comment]
I did the same thing lol!

**Comment by argiepiano** [comment]
This was fixed in #34
