### ISSUE TITLE
Replace ENTITY_IN_CODE with ENTITY_PLUS_IN_CODE

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api#43]
In the code for this module, there are still a few instances of  `ENTITY_IN_CODE`. These should be replaced with the constant `ENTITY_PLUS_IN_CODE`, which is defined by `entity_plus`

**Comment by argiepiano** [comment]
PR #43. @herbdool, please review if you have a chance.

**Comment by herbdool** [comment]
This looks good to me!
