### ISSUE TITLE
callback_add_hierarchy.inc contains an inexistent callback

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api#47]
The method `SearchApiAlterAddHierarchy::propertyInfo()` contains the callback `'entity_property_verbatim_get'`. The correct callback in BAckdrop's Entity Plus is `entity_plus_property_verbatim_get`.

**Comment by argiepiano** [comment]
PR #48 ready for testing.

**Comment by argiepiano** [comment]
@herbdool, since I created the PR, I can't merge as part of the @backdrop-contrib/bug-squad. This was provided a few months ago - very simple change similar to others already merged. Can you merge? We should also consider doing a release of this module. The current maintainer doesn't seem to be active here anymore. @laryn asked to become co-maintainer last week.

**Comment by herbdool** [comment]
I've merged on behalf of @backdrop-contrib/bug-squad. Thanks @argiepiano
