### ISSUE TITLE
Co-maintainer?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/search_api#50]
@earlyburg Are you interested in taking on a co-maintainer? If so I would be interested in helping get some of the issues/PR on this module unstuck.

**Comment by argiepiano** [comment]
@laryn, it seems like @earlyburg is not active in the community anymore. Why don't you create a PR with you as co-maintainer, and we can follow the bug squad policy of merging it after a period of time?

**Comment by argiepiano** [comment]
@earlyburg, please let us know if you have any thoughts about @laryn becoming a co-maintainer. As part of the @backdrop-contrib/bug-squad I plan to merge this PR this week, as it's been 2 weeks since it was created.

**Comment by laryn** [comment]
I also just left a quick message on his contact form with a link to this issue in case he has Github notifications/emails turned off.

**Comment by herbdool** [comment]
I've merged the PR. It's been 2 weeks, as @argiepiano mentioned, with no response. The steps spelled out in https://docs.backdropcms.org/documentation/abandoned-projects have been followed.
