### ISSUE TITLE
Switch dropbuttons to use Backdrop's theming

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/search_api#53]
It looks like the code includes some customized dropbutton theming that we can maybe remove in favor of Backdrop's dropbuttons.

**Comment by laryn** [comment]
@argiepiano Are you interested in testing this PR?

**Comment by argiepiano** [comment]
I'm getting some broken images when I applied this patch to the dev version - perhaps these are broken in the dev version?

<img width="519" alt="Screen Shot 2023-11-29 at 4 41 57 PM" src="https://github.com/backdrop-contrib/search_api/assets/9938978/d0791bd3-a505-4a19-8072-17fa8b6e5cea">

**Comment by argiepiano** [comment]
@laryn, the culprit is a commit done in October, which removed a trailing slash from $base_path: 5f452a4385b01e6742256b1bf862cf51cfd8c924

Can you perhaps fix this this problem in this PR, since it's somewhat related?

EDIT: lines 48 and 55 need `'/'` before the file name.

**Comment by laryn** [comment]
@argiepiano I noticed that, too, and actually included it (although unrelated) in the other PR. Since it's not technically related to either of these PRs and has not been included in any actual release, I'm comfortable leaving it there.

**Comment by laryn** [comment]
Did everything else look good?

**Comment by argiepiano** [comment]
Hi. Yes, everything worked fine. Sorry for the delay in responding.
