### ISSUE TITLE
Deprecated function: Creation of dynamic property SearchApiQueryFilter::$tags is deprecated in SearchApiQueryFilter->__construct() 

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api#57]
This is thrown when enabling a filter in PHP 8.2.

**Comment by argiepiano** [comment]
This is the [corresponding issue in D7](https://www.drupal.org/project/search_api/issues/3402005). I don't agree with the fix there. It makes more sense to define property $tags, since it's integral to the functioning of the class.

**Comment by argiepiano** [comment]
PR ready: https://github.com/backdrop-contrib/search_api/pull/58

**Comment by laryn** [comment]
Thanks @argiepiano!
