### ISSUE TITLE
Search api should not set the info for search server modules as `required`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/search_api#60]
This is a similar issue as the one discovered in [Feeds](https://github.com/backdrop-contrib/feeds/issues/141). The problem here is that search_api checks if there is a search server currently in use by indexes, and if it finds any, then it marks the server module's `info` as `required`. In Backdrop, this has the effect of completely **hiding** the module, rather than disabling the checkbox to disable it. This produces WTF moments, as it's impossible to tell what database_search, for example, is enabled but not shown.

**Comment by argiepiano** [comment]
In Backdrop, the `info` should be switched to `disabled` - which disables the checkbox, but still shows the module.

**Comment by argiepiano** [comment]
@laryn, PR #61 is ready for review.

**Comment by laryn** [comment]
Thanks @argiepiano!
