### ISSUE TITLE
Overview table issues

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/search_api#7]
The overview table (`/admin/config/search/search_api`) has some issues:

![image](https://user-images.githubusercontent.com/2385329/94520229-3ba18a80-026f-11eb-8978-b2815a04fa1a.png)

I think the whole `search_api_admin_overview()` function needs some cleaning up/simplifying...

**Comment by earlyburg** [comment]
Is this a layout issue? Mine shows the index listing right justified but that is all.

This pull request might help: https://github.com/backdrop-contrib/search_api/pull/6

![image](https://user-images.githubusercontent.com/36900097/95009690-08a22280-05f2-11eb-88ac-2235fbfecf59.png)
