### ISSUE TITLE
Maintainers

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/search_api#9]
Hi @earlyburg - thanks for taking on the maintenance of this module. Though I'm just trying to find the issue where the previous maintainer @docwilmot and you agreed to add you as a maintainer. Perhaps this was done outside of this channel. Regardless it would be good to make it official here.

I can't find the exact wording here https://github.com/backdrop-ops/contrib (perhaps @klonos can point me to it) but from what I understand someone needs to first create an issue with a request to be added as a maintainer. Either the maintainer responds with yes/no, or if no response after a couple weeks, a Backdrop Contrib Administrator can edit the project to add that person.

So far your changes look great @earlyburg so I've got nothing against that. Just hoping to get the paper trail.

**Comment by earlyburg** [comment]
Hi @herbdool
Here is a link to the issue where Docwilmot and I discussed having me take this over with his oversight and guidance:
https://github.com/backdrop-contrib/search_api/pull/6
I'm both grateful and excited to be a part of the team here. 
Once you have reviewed the pull request where we had the dialog, let me know how I can best help out.

**Comment by herbdool** [comment]
@earlyburg thanks for clarifying and thank you for getting this project working!

**Comment by earlyburg** [comment]
Closing this as this is resolved by https://github.com/backdrop-contrib/search_api/issues/10
